name: Autodeploy de mi proyecto
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy nodejs app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USER}}
          
          script: |
            cd /var/www/html/node-facilito
            pm2 stop node-facilito
            git pull origin master
            npm install
            pm2 start node-facilito